config/routes.rb
Levels::Application.routes.draw do
   root :to => 'home#index'
   resources :users
   resources :posts
   # get '/posts/author/:id' => 'posts#author'

   get '/users' => 'home#index'

 get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :string(255)
#  post_id     :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Comment < ActiveRecord::Base
	belongs_to :post
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  title      :string(255)
#  body       :text
#  image      :string(255)
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#  tumblr_id  :string(255)
#

class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)
#  email           :string(255)
#  avatar          :string(255)
#  body            :string(255)
#  password_digest :string(255)
#  is_admin        :boolean          default(FALSE)
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
	has_many :posts
	mount_uploader :avatar, AvatarUploader

	  has_secure_password
	  # validates :avatar, :presence => true
	  validates :username, :presence => true, :length => { :minimum => 2 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action	:authenticate_user

	private
		def authenticate_user
			if session[:user_id].present?
				@current_user = User.where(:id => session[:user_id]).first
			end

			if @current_user.nil?
				session[:user_id] = nil
			end
		end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
	if @current_user && @current_user.is_admin?
		redirect_to users_path
	end

end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :check_if_logged_in


   def index
    
    @key = 'Do1mHRSlF1wBiwFq7WuxApvRIRQJFfN5ywZxgm1LqitSHQPyRs'
     @secret = 'Do1mHRSlF1wBiwFq7WuxApvRIRQJFfN5ywZxgm1LqitSHQPyRs'
     @oauth_token = 'Do1mHRSlF1wBiwFq7WuxApvRIRQJFfN5ywZxgm1LqitSHQPyRs'
     @oauth_token_secret = 'Do1mHRSlF1wBiwFq7WuxApvRIRQJFfN5ywZxgm1LqitSHQPyRs'

     @myClient = Tumblr::Client.new({
     :consumer_key => @key,
     :consumer_secret => @secret,
     :oauth_token => @oauth_token,
     :oauth_token_secret => @oauth_token_secret
     })

      @tumblr_post = @myClient.posts('davidmes.tumblr.com', :limit => 6)
      @tumblr_post['posts'].each do |post|
        existing_post = Post.find_by(:tumblr_id => post['id'].to_s)
        if existing_post.nil?
          local_post = Post.create(:name => post['blog_name'], :title => post['slug'], :tumblr_id => post['id'], :body => post['caption'])
          User.first.posts << local_post # Fix this.
        end
      end
      @posts = Post.all
   end 

   def create
    post = Post.create post_params
    redirect_to post
   end

  def new
    @user = @current_user
    @post = Post.new
  end

  def edit
    @post = Post.find params[:id]
  end

  def show
    @post = Post.find params[:id]
  end
  
  def update
    post = Post.find params[:id]
    post.update post_params
    redirect_to post
  end
  
  def destroy
    post = Post.find params[:id]
    post.destroy
    redirect_to posts_path
  end

  def author
    @posts = Post.where(:user_id => params[:id])
    render :index
  end

  private
  def post_params
    params.require(:post).permit(:name, :title, :body, :image, :user_id)
  end

    def check_if_logged_in
    redirect_to(new_user_path) if @current_user.nil?
  end

  def check_if_admin
    redirect_to(root_path) unless @current_user.is_admin?
  end



end

app/controllers/session_controller.rb
class SessionController < ApplicationController

	def new
	end


	def create
		user = User.find_by(:username => params[:username])
	    if user.present? && user.authenticate(params[:password])
	      session[:user_id] = user.id
	      redirect_to root_path
	  	else
		  	flash[:notice] = "Invalid Login Buddy. Dave says try again."
		  	redirect_to login_path
		end
	end

	def destroy
	    session[:user_id] = nil
	    redirect_to root_path
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :check_if_logged_in, :except => [:new, :create]
  before_action :check_if_admin, :only => [:index]


   def index
	  @users = User.all
   end

   def create
   	@user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end


    # user = User.create user_params
    # redirect_to user
   end

  def new
    @user = User.new
  end

  def edit
    @user = User.find params[:id]
  end

  def show
    @user = User.find params[:id]
  end

  def update
    user = User.find params[:id]
    user.update user_params
    redirect_to user_path
  end

  def destroy
    user = User.find params[:id]
    user.destroy
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :body, :avatar, :avatar_cache, :password, :password_confirmation)
  end

  def check_if_logged_in
    redirect_to(new_user_path) if @current_user.nil?
  end

  def check_if_admin
    redirect_to(root_path) unless @current_user.is_admin?
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
	def smartnav
	    links = ''
	    if @current_user.try(:is_admin)
	      links += "<li>" + link_to('View users', users_path) + "</li>"
    end

    if @current_user.present?
      links += "<li>"
      links += link_to('Logout ' + @current_user.username, login_path, :data => {:method => :delete, :confirm => 'Really logout?'})
      links += "</li>"
    else
      links += "<li>#{ link_to('Sign up', new_user_path) }</li>"
      links += "<li>#{ link_to('Sign in', login_path) }</li>"
    end

    links
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>WELCOME TO LEVELS!</h1>
<h4>we are all about BLOGS</h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Levels</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  
</head>


<body>
<header>
  <div class="row">
    <div class="large12">

   <!--  <img src="assets/treetants2.jpg"> -->
     </div>
  </div>
<header>

<div id="container">



  
<div class="menu">
    <nav>
      
        <li><%= link_to('Home', '/') %></li>
        <% if @current_user.nil? %>      
          <li><%= link_to('Create a new User', new_user_path) %></li>
          <li><%= link_to('Login as an existing User', login_path) %></li>
        <% end %>
        <% if @current_user.present? %>
          <li><%= link_to('Post Feed', posts_path) %></li>
          <li><%= link_to('Add a New Post', new_post_path) %></li>
          <li><%= link_to('Sign Out', login_path, :method => :delete) %></li>
          <% if @current_user.is_admin? %>
            <li><%= link_to('Users', users_path) %></li>
          <% end %>
        <% end %>
      
    </nav>
</div>
   
    <%= yield %>
  
  </div>

    <% if flash[:notice].present? %>
    <div class="notice">
      <%= flash[:notice] %>
    </div>
  <% end %>

</body>
</html>

app/views/posts/_form.html.erb
<div class="background">

   <div class="show">
    <%= form_for @post do |f| %>
    <% @post.errors.full_messages.each do |error| %>
      <li><%= error %></li>
      <% end %>

      <p><%= f.label :user_id %>
      <%= f.select :user_id, User.all.map{|user|[user.username, user.id]}, :include_blank => true %>

     </p>
     <p>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </p>

    <%=f.label :body %><br/>
    <%=f.text_area :body %>
    </p>

    <p>
     <%= f.label :image %>
    <%= f.text_field :image %>
   </p>

   
    <p> <%= f.submit %> </p>

    <% end %>

</div>

</div>

app/views/posts/edit.html.erb
<h2>Update Post! </h2>
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<div class="user">

<h1> Post Feed </h1>

<ul>


  <% @posts.each do |post| %>


  <div class="userfont">

     <li>User: <%= link_to(post.user.username, post_path(post)) if post.user %> </li>
     
     <div class="truncate">
     <li><%= image_tag(post.user.avatar_url, :class => 'thumb') if post.user   %></li>
     <li>Title: <%= link_to(truncate(raw(post.title)), post_path(post), escape: false) %></li>

  
    <li>Post: <%= truncate(raw(post.body), escape: false) %> </li>
   </div>
    
    
     <%= link_to'Delete', post, :class => 'delete',:method => :delete, :confirm => "Are you sure you want to delete this Post?" %>

<hr>
   	

   <% end %>

   

 <!-- <div id="stay"> -->
 <!-- <button class="closemenu">Show Tumblr</button>
<br>
<br>
 <hr>
      <div class="tumblr">
		<h1>Tumblr Post</h1>
		   

		   <% @tumblr_post['posts'].each do |post|  %>
			<li> Tumblr Name: <%= link_to post["blog_name"], post['post_url'] %> </li>
			<li> Tumblr Tilte: <%=  link_to truncate(raw(post["slug"])), post['post_url'] %> </li>
			
		
			 
			<li> Blog:<%= truncate(raw(post['caption']), escape: false) %></li>
			<hr>
       
        

		 
		  
		<% end %>

     </div>
 -->
    </div>

<!-- @tumblr_post == {blog=>{},posts=>{},total_posts=>'8'} -->

  </ul>

</div>

   <!--  <%= @tumblr_post %> -->


   

app/views/posts/new.html.erb
<div class="create">
<h1>Create a new Post!</h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<h1 class='create'><%= link_to(@post.user.username, @post.user) if @post.user %></h1>	
<div class="userfont">

<ul>



<li><%= image_tag(@post.user.avatar_url, :class => 'thumb') %><li>

<hr>

<li>Title: <%= @post.title %></li>

<li> Post: <%= raw(@post.body) %></li>

<li><%= image_tag(@post.image, :class => 'xthumb') %></li>

<%= link_to'Edit |', edit_post_path %>
<%= link_to'Delete', @post, :method => :delete, :confirm => "Are you sure you want to delete this Post?" %></p>

<li> <%= link_to('Create a new Post', new_post_path) %></li>

<li><%= link_to " Back to post feed", posts_path %></li> 

 </div>


<hr>


</ul>


	







	

app/views/session/new.haml
= form_tag '/login' do
  = label_tag 'username'
  = text_field_tag 'username', nil, :autofocus => true

  = label_tag 'password'
  = password_field_tag 'password'

  = submit_tag 'Login'

app/views/users/_form.html.erb
<div class="background">

<div class="show">
<%= form_for @user do |f| %>

    <%= f.text_field :username,  :placeholder => "Full Name", :autofocus => true, :class => "css_class" %>
  </p>

  <p>
    
    <%= f.text_field :email, :placeholder => "Email", :class => "css_class" %>
  </p>

     
    <%= f.file_field :avatar, :class => "css_avatar"  %>
    <%= f.hidden_field :avatar_cache, :class => "css_avatar" %>
  </p>
  
 

  <p><%= f.button 'Create User' %></p>
<% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h2>Update User </h2>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<div class="user">

<h1>Levels</h1>

<ul>
   <% @users.each do |user| %>

 
<div class="userfont">
   	<li>Profile : <%= link_to(user.username, user) %></li>
   	<li><%= image_tag(user.avatar, :class => 'thumb')  %></li>
   	<li>Email: <%= user.email %>

    <li><%= link_to('Add New Post', new_post_path) %></li>
  
  

  
  <%= link_to('Edit |', edit_user_path(user)) %> 
    
	<%= link_to('Delete', user, :method => :delete, :confirm => "Are you sure you want to delete this Profile?") %> 
</div>

  <hr>

   	

   	


   <% end %>

</ul>
</div>

app/views/users/new.haml
- if @user.errors.any?
  %h1 YOU MASSIVE IDIOT
  %ol
    - @user.errors.full_messages.each do |msg|
      %li= msg

%div.row
  %div.col-md-9
    = form_for @user do |f|
      %div.formgroup
        = f.label :username
        = f.text_field :username, :autofocus => true, :class => 'form-control'

      %div.formgroup
        = f.label :avatar
        = f.file_field :avatar, :class => 'form-control'

      %div.formgroup
        = f.label :password
        = f.password_field :password, :class => 'form-control'

      %div.formgroup
        = f.label :password_confirmation
        = f.password_field :password_confirmation, :class => 'form-control'

      = f.submit :class => 'btn btn-success'

  %div.col-md-3
    %p Please sign in before you do anything else

app/views/users/news.html.erb
<div class="create">
<h2>Create a new User</h2>
</div>

<%= render :partial => 'form' %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div class="user">
<h1><%= @user.username %></h1>
<ul>
  <div class="userfont">
  <li><%= image_tag(@user.avatar, :class => 'thumb') %></li>
  <li><%= @user.email %></li>
<hr>
  <p class="plist"> POSTS </p>

  <% @user.posts.each do |post| %>
  
       <p><%= link_to(post.title, post) %></p>
  
   <% end %>
   <hr>
   <li> <%= link_to('Create a new Post', new_post_path) %></li>
   <li><%= link_to('View Your Post Feeds', posts_path) %></li>
        
   </div>
   	 
<hr>
  
</ul>

</div>